Rework core patches to be patched in via the linker
minecraft-linux/mcpelauncher-client pull request #18
Opened 2021-03-12 18:59 UTC by bylaws

This fixes mouse support for 1.16.210+ versions.

The callbacks themselves are passed as an argument when loading the Minecraft library.

2021-03-16 14:24 UTC, ChristopherHX requested changes
If you recover `CorePatches::install(void *handle)` + calles to it, I would merge this.

You can reuse showMousePointer and hideMousePointer in `CorePatches::install`

_I have my own local version of such a patch from last Friday_

2021-03-16 14:24 UTC, ChristopherHX commented on src/core_patches.cpp
> -        Log::error("CorePatches", "Failed to patch vtable _ZTV21AppPlatform_android23 not found");
I disagree that you want to remove `CorePatches::install(void *handle)`,
I told you on discord that this method breaks Mouse Capture in Minecraft PE 0.12 armeabi-v7a, which might be added back to ng. (The only reason why it does not work is the different (incomplete) jni glue code in ng)

My suggestion is to keep and calling it, to increase the success rate for Mouse Capture patching. If hooking works, then `CorePatches::install(void *handle)` is a noop, but on Minecraft PE 0.12 armeabi-v7a it would succeed even if hooking failed.

Vtable patching far more solid for 0.12-1.16.201, than the hooking method which depends heavily on mojangs compiler or toolset.

2021-03-16 20:25 UTC, bylaws commented on src/core_patches.cpp
> -        Log::error("CorePatches", "Failed to patch vtable _ZTV21AppPlatform_android23 not found");
Right, will do that

2021-03-16 21:25 UTC, bylaws commented
Resolved feedback

2021-03-17 22:35 UTC, ChristopherHX approved these changes

2021-03-17 22:35 UTC, merged

2021-03-17 22:37 UTC, ChristopherHX commented
Thanks looks good, but 1.16.210 will be hidden (in dev mode) again soon, you can hardly craft anything in survival :/